### ISSUE TITLE
Counter should be floating point

### ISSUE THREAD

**Issue by jml** [fimad/prometheus-haskell#10]
In Prometheus, everything is a 64 bit floating point. The documentation for https://prometheus.io/docs/concepts/metric_types/#counter doesn't say that it's restricted to integrals and thus should probably be a float.

**Comment by fimad** [comment]
Right now the only API for mutating a counter is `incCounter` so there doesn't seem to be much practical difference between an int and a float.

Are you concerned about overflow behavior than representing floating point values?

**Comment by jml** [comment]
Concerned about representing floating point values. For example, a common way to calculate mean time spent doing a thing in Prometheus is to store total seconds taken in a counter and divide by number of times attempted. 

The [best practices guide](https://prometheus.io/docs/practices/naming/) advocates using base units (e.g. `seconds` not `milliseconds`) for metrics, and illustrates this with a counter `process_cpu_seconds_total`. That would be not terribly useful if it could only go up in whole seconds.

**Comment by fimad** [comment]
Makes sense, I'd be happy to take a PR that changes from ints to doubles.

**Comment by jml** [comment]
Thanks! PR submitted.
