### ISSUE TITLE
Histogram uses wrong names, causing breakage in Prometheus 2.0

### ISSUE THREAD

**Issue by arianvp** [fimad/prometheus-haskell#23]
Currently the names are:

```
x
x_count
x_sum
```

but they have to be

```
x_bucket
x_count
x_sum
```
(https://prometheus.io/docs/practices/histograms/)

In prometheus `< 2.0` this was not a problem. The name `x` was implicitly upcasted to `x_bucket`.

In prometheus `2.0` this is not the case anymore. We should fix the naming

**Comment by arianvp** [comment]
it should be an easy fix.  I can make a PR

**Comment by jml** [comment]
Ugh, sorry.
