### ISSUE TITLE
Unused settings?

### ISSUE THREAD

**Issue by qrilka** [fimad/prometheus-haskell#26]
In `PrometheusSettings` I see `prometheusInstrumentApp` and `prometheusInstrumentPrometheus` but those flags seem to be never used.
I'd like to have `/metrics` endpoint which responds only with the metrics I specify but it looks like that out of the box `prometheus` from `Network.Wai.Middleware.Prometheus` always instruments both metrics and app (which in my case would be just returning 404 for every request).

**Comment by fimad** [comment]
That's embarrassing, it indeed look like these values are unused...

**Comment by qrilka** [comment]
@fimad do you want me to create a PR fixing this?

**Comment by fimad** [comment]
If you like that would be great, otherwise I can.
