### ISSUE TITLE
Export metrics as protobufs

### ISSUE THREAD

**Issue by jml** [fimad/prometheus-haskell#27]
Exporting as text is fine for now, but would welcome protobuf export, mostly for bragging rights about Haskell, but also because it should probably mean less CPU for everyone.

**Comment by ocharles** [comment]
I'd like to see some proof that this is actually worth doing. I was told by @brian-brazil on IRC a few weeks back that there's not really any point for client libraries to have this added - the text parser is even better in Prometheus 2.0. I've tagged Brian specifically to see if he has any points I missed, excuse the rather direct outreach.

**Comment by brian-brazil** [comment]
There's not much point in doing this. Even if Prometheus still used it, the cpu savings are minimal.

**Comment by jml** [comment]
Thanks!
