### ISSUE TITLE
Export process metrics

### ISSUE THREAD

**Issue by jml** [fimad/prometheus-haskell#33]
From https://prometheus.io/docs/instrumenting/writing_clientlibs/#standard-and-runtime-collectors:

### Process metrics

These exports should have the prefix `process_`. If a language or runtime
doesn't expose one of the variables it'd just not export it. All memory values
in bytes, all times in unixtime/seconds.

| Metric name                     | Help string                                            | Unit             |
| ------------------------------- | ------------------------------------------------------ | ---------------  |
| `process_cpu_seconds_total`     | Total user and system CPU time spent in seconds.       | seconds          |
| `process_open_fds`              | Number of open file descriptors.                       | file descriptors |
| `process_max_fds`               | Maximum number of open file descriptors.               | file descriptors |
| `process_virtual_memory_bytes`  | Virtual memory size in bytes.                          | bytes            |
| `process_resident_memory_bytes` | Resident memory size in bytes.                         | bytes            |
| `process_heap_bytes`            | Process heap size in bytes.                            | bytes            |
| `process_start_time_seconds`    | Start time of the process since unix epoch in seconds. | seconds          |

It would be great to export these by default.

**Comment by fimad** [comment]
Do you know how to get access to these stats?

**Comment by jml** [comment]
Not in a platform independent way.

The Python and Go libraries both inspect the /proc filesystem—an easy
enough thing to do in Haskell.

**Comment by ocharles** [comment]
Perhaps this is best to be in `prometheus-proc`? At least, until we can find something more portable.

**Comment by ocharles** [comment]
I've started work on this at https://github.com/fimad/prometheus-haskell/pull/42. It exports from `/proc/<pid>/stat`, but doesn't read limits yet. If anyone wants to try this, let me know how you get on!

**Comment by ocharles** [comment]
https://hackage.haskell.org/package/prometheus-proc-0.1.0.0
