### ISSUE TITLE
Use RTSStats with base 4.9 and later

### ISSUE THREAD

**Issue by jml** [fimad/prometheus-haskell#34]
`GCStats` is deprecated as of base 4.10 (see https://www.stackage.org/haddock/lts-11.2/base-4.10.1.0/GHC-Stats.html) and has been replaced with `RTSStats`.

It would be good to support `RTSStats` when running later versions.

**Comment by jml** [comment]
I wonder whether it makes more sense to do this with CPP, or instead to make a wholly new ghc-metrics library. Thoughts?

**Comment by ocharles** [comment]
@jml I believe with @zyla and @purcell's recent PR, this is done - right?

**Comment by jml** [comment]
That’s my understanding. I haven’t tested.
