### ISSUE TITLE
Move to Prometheus organization / governance?

### ISSUE THREAD

**Issue by jml** [fimad/prometheus-haskell#37]
@fimad What do you think of opening up commit & release access?

We've all got busy day jobs, but perhaps together we could release more often and merge PRs. 

One way to do this would be to move this project to the Prometheus project & governance model. This would probably mean:
- the repo would be at prometheus/prometheus-haskell
- the existing Prometheus team members and maintainers would get commit access
- we could add maintainers specific to prometheus-haskell (I'd suggest myself & @ocharles)

I asked on IRC, and this isn't an a priori terrible idea, but it is something that would have to be proposed and voted on by the Prometheus team members.

Other options would be adding collaborators, or creating a new organization and moving there.

Let me know what you think. If you want to try moving into the Prometheus project, I can draft a proposal and try to get a team member to propose it.

**Comment by jml** [comment]
> I asked on IRC, and this isn't an a priori terrible idea, but it is something that would have to be proposed and voted on by the Prometheus team members.

Later discussion revealed a strong pushback against adding _any_ more projects to the prometheus organization, so if we do want to open up commit access, we'll probably have to go for the other options: new GitHub org or manual collaborators.

**Comment by ocharles** [comment]
Probably best to just add people to this repo then

**Comment by fimad** [comment]
Sounds good to me, i'll add you both as collaborators here and on hackage. What are your hackage accounts?

**Comment by jml** [comment]
I’m jml on Hackage. Thanks!

**Comment by ocharles** [comment]
I'm OliverCharles on Hackage

**Comment by fimad** [comment]
Alright, you should both be added to the relevant hackage packages and have invites to this repo. Let me know if you don't see the invite or I missed anything.

**Comment by jml** [comment]
Thanks! As you can see, we've both got collaborator rights now. Checking
Hackage permissions is hard, but we can lazily evaluate those.

**Comment by jml** [comment]
I stand corrected: https://hackage.haskell.org/user/jml shows I have upload rights.
