### ISSUE TITLE
Is it possible to add labels to ghcMetrics? If yes, how?

### ISSUE THREAD

**Issue by alaendle** [fimad/prometheus-haskell#52]
Sorry if this is a silly question, but I found no obvious way to add labels to the metrics exposed by ghcMetrics. I plan to aggregate the exposed prometheus text of multiple service instance and so I'm looking for a way to distinguish the instances - I think prometheus labels might be a good way to do so. For sure labels could maybe added during scraping; but I think the running application has much more context information to add reasonable labels/values.

**Comment by ocharles** [comment]
Fixed by #53
