### ISSUE TITLE
Add packages to Stackage LTS

### ISSUE THREAD

**Issue by kamek-pf** [fimad/prometheus-haskell#61]
Hello !

It looks like `prometheus-client` is available in the current Stackage LTS, however `prometheus-metrics-ghc` and `wai-middleware-prometheus` are not. It's be great to have all 3 since they're meant to be used together.

Adding a package looks simple enough, the Stackage team recommends maintainers to add their own packages :
https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md#adding-a-package

Would you mind taking a look ?

**Comment by fimad** [comment]
Sure thing. They all use to be, the others must have been disabled due to some build conflicts.

**Comment by ocharles** [comment]
I think this was fixed by https://github.com/commercialhaskell/stackage/pull/6054. If this still needs work, please comment and I'll re-open!
